### PR TITLE
Update JOSM core icons

### PR DESCRIPTION
**Pull request by don-vip**

### CODE REVIEW

**Comment by don-vip** [comment]
We plan to release new JOSM very soon, can this PR please be merged? It helps us to maintain all extensions out there. Thanks.

**Comment by don-vip** [comment]
See https://github.com/hotosm/presets/pull/30 for details. Like HOT, you will need to make a release, and link the zip archive to JOSM wiki.

**Comment by Edouard-Legoupil** [comment]
accepted pull request

**Comment by don-vip** [comment]
Thanks. Is there a timeframe where the PR will actually be merged?

**Comment by don-vip** [comment]
Hi Edouard,
We have a new unit test that fails every day on JOSM continuous integration because of these errors. Can you please merge the PR, then make a release that will include all missing icons in a zip archive?
We also have asked this to HOT in https://github.com/hotosm/presets/pull/30 and https://github.com/hotosm/presets/issues/31

**Comment by don-vip** [comment]
Only valid presets are now accepted in the default list.
I have removed HOT presets and some others until this issue is solved:
https://josm.openstreetmap.de/wiki/PresetsSource?action=diff&version=8

**Comment by don-vip** [comment]
Closing this issue. Please reopen anf merge if this project is still maintained.

**Pull request closed without merging**
